# Generated by Django 3.0.8 on 2022-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreId', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('url', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tracks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artistName', models.TextField()),
                ('name', models.TextField(max_length=100)),
                ('kind', models.TextField(max_length=100)),
                ('artistId', models.TextField(max_length=100)),
                ('artistUrl', models.TextField(max_length=100)),
                ('contentAdvisoryRating', models.TextField(max_length=100)),
                ('artworkUrl100', models.TextField(max_length=100)),
                ('url', models.TextField(max_length=100)),
            ],
        ),
    ]
