# Generated by Django 3.0.8 on 2022-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaFunc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genres',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='artistId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='artistUrl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='artworkUrl100',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='contentAdvisoryRating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='kind',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='url',
            field=models.TextField(),
        ),
    ]
